type KhataPdfEntry = {
  debtor: string;
  creditor: string;
  amount: number;
  note: string | null;
  paid: boolean;
  created_at: string;
};

type KhataPdfBalance = {
  name: string;
  net: number;
};

function escapePdfText(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function fmtInr(n: number): string {
  return `Rs. ${n.toFixed(2)}`;
}

/** Minimal PDF statement for chat khata (no external deps). */
export function buildKhataPdf(opts: {
  chatTitle: string;
  periodLabel: string;
  entries: KhataPdfEntry[];
  balances: KhataPdfBalance[];
  totalPending: number;
}): Buffer {
  const lines: { size: number; text: string; y: number; right?: boolean }[] = [
    { size: 18, text: "Videh Khata Statement", y: 760 },
    { size: 12, text: opts.chatTitle.slice(0, 72), y: 736 },
    { size: 10, text: `Period: ${opts.periodLabel}`, y: 716 },
    { size: 10, text: `Total pending: ${fmtInr(opts.totalPending)}`, y: 698 },
    { size: 11, text: "Net balances (pending)", y: 672 },
  ];

  let y = 654;
  for (const b of opts.balances.slice(0, 8)) {
    const label = b.net >= 0 ? `${b.name}: receives ${fmtInr(b.net)}` : `${b.name}: owes ${fmtInr(Math.abs(b.net))}`;
    lines.push({ size: 10, text: label.slice(0, 90), y });
    y -= 16;
    if (y < 520) break;
  }

  y = Math.min(y - 10, 500);
  lines.push({ size: 11, text: "Entries", y });
  y -= 18;

  for (const e of opts.entries.slice(0, 18)) {
    const status = e.paid ? "PAID" : "DUE";
    const row = `${status} | ${e.debtor} -> ${e.creditor} | ${fmtInr(e.amount)}`;
    lines.push({ size: 9, text: row.slice(0, 95), y });
    y -= 14;
    if (e.note) {
      lines.push({ size: 8, text: `  ${e.note}`.slice(0, 95), y });
      y -= 12;
    }
    if (y < 60) break;
  }

  lines.push({ size: 8, text: "Generated by Videh Messenger", y: 36 });

  const textOps = lines
    .map((line) => {
      const x = line.right ? 480 : 48;
      return `/F1 ${line.size} Tf 1 0 0 1 ${x} ${line.y} Tm (${escapePdfText(line.text)}) Tj`;
    })
    .join("\n");

  const stream = `BT\n${textOps}\nET`;
  const streamLen = Buffer.byteLength(stream, "utf8");

  const objects = [
    "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n",
    "2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n",
    "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj\n",
    `4 0 obj\n<< /Length ${streamLen} >>\nstream\n${stream}\nendstream\nendobj\n`,
    "5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n",
  ];

  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [0];
  for (const obj of objects) {
    offsets.push(Buffer.byteLength(pdf, "utf8"));
    pdf += obj;
  }

  const xrefStart = Buffer.byteLength(pdf, "utf8");
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += "0000000000 65535 f \n";
  for (let i = 1; i <= objects.length; i++) {
    pdf += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\n`;
  pdf += `startxref\n${xrefStart}\n%%EOF`;

  return Buffer.from(pdf, "utf8");
}
