import { Router, type IRouter } from "express";
import healthRouter from "./health";
import otpRouter from "./otp";
import usersRouter from "./users";
import chatsRouter from "./chats";
import statusesRouter from "./statuses";
import callsRouter from "./calls";
import callLinksRouter from "./callLinks";
import webrtcRouter from "./webrtc";
import webSessionRouter from "./web-session";
import scheduledRouter from "./scheduled";
import khataRouter from "./khata";
import translateRouter from "./translate";
import sosRouter from "./sos";
import broadcastsRouter from "./broadcasts";
import adminRouter from "./admin";
import grievanceRouter from "./grievance";
import developerLeadsRouter from "./developer-leads";
import developerBillingRouter from "./developer-billing";
import developerAuthRouter from "./developer-auth";
import assistantRouter from "./assistant";
import gifsRouter from "./gifs";
import linkPreviewRouter from "./linkPreview";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/otp", otpRouter);
router.use("/users", usersRouter);
router.use("/chats", chatsRouter);
router.use("/statuses", statusesRouter);
router.use("/calls", callsRouter);
router.use("/call-links", callLinksRouter);
router.use("/webrtc", webrtcRouter);
router.use("/web-session", webSessionRouter);
router.use("/scheduled", scheduledRouter);
router.use("/khata", khataRouter);
router.use("/translate", translateRouter);
router.use("/sos", sosRouter);
router.use("/broadcasts", broadcastsRouter);
router.use("/admin", adminRouter);
router.use("/grievance", grievanceRouter);
router.use("/developer-auth", developerAuthRouter);
router.use("/developer-leads", developerLeadsRouter);
router.use("/developer-billing", developerBillingRouter);
router.use("/assistant", assistantRouter);
router.use(gifsRouter);
router.use(linkPreviewRouter);

export default router;
